# Generated by Django 3.2.3 on 2021-05-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoStart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='home_town',
            field=models.CharField(default='Sofia', max_length=30),
            preserve_default=False,
        ),
    ]
